// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx4uTpzX7X8_Epthzu0CKcVQPtx92Kx5Y',
    appId: '1:703328438774:web:42e8dbe82138e7831e9fd7',
    messagingSenderId: '703328438774',
    projectId: 'falcaobarbershopv2',
    authDomain: 'falcaobarbershopv2.firebaseapp.com',
    storageBucket: 'falcaobarbershopv2.firebasestorage.app',
    measurementId: 'G-LKL9XXBZRB',
  );

  // VAPID key for Web Push Notifications
  // VAPID key for Web Push Notifications
  // (preencha com a vapidKey do novo Firebase)
  static const String vapidKey = 'BDayEa0JrKlDXEFmw0mZuSKf5USFDIl_TFRjhgEJNBPdPLjEHDv3YX_a2NT4q6jcmUqFXNV5l9HO7Y_ek-ucP2Q';



}